[customizations.installer.kickstart]
contents= """
lang en_GB.UTF-8
keyboard fr
timezone --utc Europe/Paris

user --name user --password pass --plaintext --groups wheel

network --bootproto=dhcp

zerombr
clearpart --all --initlabel
autopart --type=plain --fstype=xfs --nohome
"""