FROM registry.redhat.io/rhel9/rhel-bootc:latest

RUN dnf -y update && \
    dnf --enablerepo=rhacm-2.14-for-rhel-9-x86_64-rpms -y install flightctl-agent && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer && \
    dnf -y install qemu-kvm libvirt virt-install virt-viewer cockpit cockpit-machines && \
    for drv in qemu network nodedev nwfilter secret storage interface; do systemctl enable virt${drv}d{,-ro,-admin}.socket; done && \
    systemctl enable libvirtd cockpit

ADD config.yaml /etc/flightctl/